# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

jms_serializer:
    metadata:
        directories:
            sylius-promotion:
                namespace_prefix: "Sylius\\Component\\Promotion"
                path: "@SyliusPromotionBundle/Resources/config/serializer"

sylius_promotion:
    promotion_action:
        validation_groups:
            order_percentage_discount:
                - 'sylius'
                - 'sylius_promotion_action_order_percentage_discount'
            shipping_percentage_discount:
                - 'sylius'
                - 'sylius_promotion_action_shipping_percentage_discount'
            order_fixed_discount:
                - 'sylius'
                - 'sylius_promotion_action_order_fixed_discount'
            unit_fixed_discount:
                - 'sylius'
                - 'sylius_promotion_action_unit_fixed_discount'
            unit_percentage_discount:
                - 'sylius'
                - 'sylius_promotion_action_unit_percentage_discount'
    promotion_rule:
        validation_groups:
            cart_quantity:
                - 'sylius'
                - 'sylius_promotion_rule_cart_quantity'
            customer_group:
                - 'sylius'
                - 'sylius_promotion_rule_customer_group'
            nth_order:
                - 'sylius'
                - 'sylius_promotion_rule_nth_order'
            shipping_country:
                - 'sylius'
                - 'sylius_promotion_rule_shipping_country'
            has_taxon:
                - 'sylius'
                - 'sylius_promotion_rule_has_taxon'
            total_of_items_from_taxon:
                - 'sylius'
                - 'sylius_promotion_rule_total_of_items_from_taxon'
            contains_product:
                - 'sylius'
                - 'sylius_promotion_rule_contains_product'
            item_total:
                - 'sylius'
                - 'sylius_promotion_rule_item_total'
